### ISSUE TITLE
breaking tls api change in 0.12

### ISSUE THREAD

**Issue by rvagg** [dominictarr/reconnect#25]
https://github.com/joyent/node/issues/8499

The "on `secureConnect` emit `connect`" trick isn't going to work any more in tls.js. Perhaps instead of returning the socket from tls.js we return an EE that does everything that reconnect needs and then we have full control over the events. Otherwise we end up with a double `'connect'` event on 0.11/0.12 and a single `'connect'` on 0.10!

/cc @juliangruber

**Comment by dominictarr** [comment]
oh, so it emits `connect` when the tcp connection is made, and `secureConnect` when the handshake is complete? so we need to detect if this is a secure stream and then listen for `secureConnect` instead?

**Comment by rvagg** [comment]
correct, for my use this is resulting in a double-call to the `onConnect` handler passed in to `reconnect` cause it's making spitting out two `'connect'` events

**Comment by dominictarr** [comment]
oh... actually - what we can just do is ignore the second `connect` event.
reconnect uses the connect event so that the user's onConnect listener is only called when a connection is successfully made not just when an attempt is made. the connect event is emitter after the TCP SYN packet is received (the other side answering the phone).

Now we know for sure that we can write to that connection. If we didn't have this it would still work,
but it would call onConnect and then error sometimes. If we get 'connect' then we know the server is running - we may also get a TLS error - but probably that is something we _want_ to throw in the user's face...

**Comment by rvagg** [comment]
but shouldn't it still be waiting until `'secureConnect'` so we know we have a usable stream? the first `'connect'` only tells us that the connection occured, not that it's actually usable.

**Comment by dominictarr** [comment]
we _could_ wait until then, but it will just buffer the writes for a little bit until the secure channel is set up so the stream is already usable. At least we know the server is actually there, which is the most important thing.

**Comment by juliangruber** [comment]
hm so we have the special case for http already, now we're thinking about doing that for tls. i wonder if that logic could live in the `inject` handlers for each transport

**Comment by rvagg** [comment]
fwiw my quick testing says that using the first `'connect'` is _probably_ OK, I'm just not sure of the mechanics behind it

**Comment by dominictarr** [comment]
btw, last I tried the http thing seemed to be broken. request does weird magic things with streams,
when it is deciding whether to be a stream or to buffer the connection... I used hyperquest and I think that worked better though.

**Comment by dominictarr** [comment]
this is fixed in 2.0.2 after upgrading to reconnect-core@0.2.1

**Comment by rvagg** [comment]
nice work, thanks guys!
